### ISSUE TITLE
speedtest.sh line 12

### ISSUE THREAD

**Issue by rgeorgie** [pschmitt/zabbix-speedtest#2]
Ubuntu server Ubuntu 16.04.3 LTS (GNU/Linux 4.4.0-112-generic x86_64);

speedtest.sh[20968]: /etc/zabbix/bin/speedtest.sh: 12: /etc/zabbix/bin/speedtest.sh: [[: not found

changed line 12 from [[ double]] to [single], still works stable.
if [ -e "$LOCK_FILE" ]

gruss,
Rosen

**Comment by leonroy** [comment]
hi, this issue has come back since the previous fix appears to have not been carried over to the new zbx shell script
