### ISSUE TITLE
/etc/zabbix/bin/zbx-speedtest.sh: 135: /etc/zabbix/bin/zbx-speedtest.sh: [[: not found

### ISSUE THREAD

**Issue by 0xN4TH4N** [pschmitt/zabbix-speedtest#21]
Hello, my error is this : /etc/zabbix/bin/zbx-speedtest.sh: 135: /etc/zabbix/bin/zbx-speedtest.sh: [[: not found
Pls help my. Thanks

**Comment by pschmitt** [comment]
You have probably already figured this out on your own but it seems that you are using a Debian-based distro and have installed the non-debian shell script. 

Once again please read the instruction in the README.

Duplicate of https://github.com/pschmitt/zabbix-template-speedtest/issues/19
