### ISSUE TITLE
zbx-speedtest.sh failed line 135 and line 165 

### ISSUE THREAD

**Issue by eltonsjbv1** [pschmitt/zabbix-speedtest#22]
Hello, 

i need help,

where i execute zbx-speedtest.sh return error for me: 

![Capturar](https://user-images.githubusercontent.com/42739800/119350827-2b16a800-bc76-11eb-8376-9913edcc0b5b.PNG)

**Comment by pschmitt** [comment]
Hi, you are probably on Ubuntu or Debian and used the wrong script.
Use the Debian specific script (see readme).

Also you clearly didn't install the right Speedtest tool. Again: please read the instructions.
