### ISSUE TITLE
unsuported item key 

### ISSUE THREAD

**Issue by backl1n** [pschmitt/zabbix-speedtest#24]
Jai redémarrer le service vérifier les mise a jour et installer avec 2 méthode différente cela ne résout rien 
dans interface web jai toujours les elements en unsuported item key 
merci d'avance pour l'aide

**Comment by pschmitt** [comment]
Please open issues in english.
Not everyone speaks french and it might help others.

That being said it's probably a config error, hard to say without any logs or config file.

**Comment by backl1n** [comment]
I restarted the service check for updates and install with 2 different methods this does not solve anything
in web interface I always have elements in element key not supported
Thanks in advance for the help @pschmitt

**Comment by pschmitt** [comment]
Thanks for the translation.

Can't help you without zabbix-agent logs and the config files though 🤷‍♂️

**Comment by backl1n** [comment]
@pschmitt 

![image](https://user-images.githubusercontent.com/40395422/187515770-5efc7ccd-4ee5-4a46-8f5a-1e8fab8d47a7.png)
![image](https://user-images.githubusercontent.com/40395422/187515843-c5154e2f-3c4e-4760-bb2b-84c55b027357.png)

**Comment by backl1n** [comment]
> Thanks for the translation.
> 
> Can't help you without zabbix-agent logs and the config files though 🤷‍♂️

I give picture of all can you help me please I try to change type of key and its always error

**Comment by pschmitt** [comment]
:laughing: 

No, can't sorry. The screenshots are not helping at all. Again, please share some info here. No one will help you on GH, unless you make it somehow easy to do so. Share all your configs and logs - AS TEXT.

**Comment by backl1n** [comment]
your instruction for install is fake

**Comment by pschmitt** [comment]
Your zabbix installation is fake! 😍
