### ISSUE TITLE
Using Ookla's speedtest command line interface - success.

### ISSUE THREAD

**Issue by BearGFR** [pschmitt/zabbix-speedtest#5]
The github version of speedtest-cli has issues that cause it to return incorrect values in some cases.  I obtained the "official" version of the speedtest command line interface from Ookla (https://www.speedtest.net/apps/cli)  and have it working like a champ on my system now.  It did require changes to the script, some additional directories/permissions to make it all work, but working it is.  I don't mind sharing, if anyone is interested.

**Comment by pschmitt** [comment]
Just open a PR, FFS.
